shorthand/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from shorthand.shorthand import views

# Список URL'ов для основого приложения
shorthand_urls = patterns(
    '',

    url(r'^$', views.ShorthandUrlListView.as_view(), name='list'),

    url(r'^(?P<pk>\d+)/$', views.ShorthandUrlDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/delete$', views.ShorthandUrlDeleteView.as_view(), name='delete'),

    url(r'^create/$', views.ShorthandUrlCreateView.as_view(), name='create'),
)

# Глобальный список URL'ов проекта
urlpatterns = patterns(
    '',

    url(r'^$', views.HomepageView.as_view(), name='homepage'),
    url(r'^shorthands/', include(shorthand_urls, namespace='shorthand')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^(?P<shortcut>[A-Z0-9]*)/', views.ShorthandUrlRedirectView.as_view(), name='shortcut-redirect'),
)

shorthand/shorthand/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import query
from model_utils import fields, managers
import string


# Собираем цифры которые будут использоваться для сокращенного кода
NOTATION_DIGIT = string.digits + string.ascii_uppercase

# Количество цифр в системе счисления
NOTATION_RADIX = len(NOTATION_DIGIT)


class ShorthandUrlQuerySet(query.QuerySet):
    """
    QuerySet для кратких ссылок
    """
    def order_by_popularity(self):
        """
        Сортировка по популярности

        :return: ShorthandUrlQuerySet
        """
        return self.order_by('-views_counter', 'created_at')

    def first_populars(self, count=20):
        """
        Получение queryset'а с первыми по популярности краткими ссылками.

        :param count: Количество элементов в результате, по умолчанию 20
        :return: ShorthandQuerySet Новый queryset
        """
        queryset = self.order_by_popularity()
        return queryset[:count]


class ShorthandUrl(models.Model):
    """
    Модель хранящая информацию об краткой ссылке
    """
    class Meta:
        verbose_name = 'Краткий URL'
        verbose_name_plural = 'Краткие URL\'ы'

    created_at = fields.AutoCreatedField('Дата создания')
    url = models.URLField('URL', help_text='Полный URL', null=False, blank=False)
    shortcut = models.CharField('URI', max_length=200, help_text='Краткий URI', db_index=True, default='', blank=True, editable=False)
    views_counter = models.PositiveIntegerField('Количество просмотров', default=0)

    objects = managers.PassThroughManager(ShorthandUrlQuerySet)

    @staticmethod
    def compute_shortcut(number):
        """
        Генерация сокрощенного URI

        :param number: Число, идентификатор краткой ссылки
        :return: Число в системе счисления с основанием NOTATION_DIGIT, для использования в качестве идентификатора
                 краткой ссылки
        """
        number = int(number)
        result = ""

        while number > 0:
            char = NOTATION_DIGIT[number % NOTATION_RADIX]
            result = char + result
            number = int(number / NOTATION_RADIX)

        return result

    def increment(self, commit=True):
        """
        Добавление кол-ва просмотров краткой ссылки

        :param commit: Если True, то изменения полей экземпляра модели немедленно сохраняются в БД
        :return: ShorthandUrl для fluent-интерфейса
        """
        self.views_counter += 1
        if commit:
            self.save()
        return self
    
    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        """
        Переопределяем метод сохранения для генерации уникального
        """
        super(ShorthandUrl, self).save(force_insert=force_insert, force_update=force_update, using=using,
                                       update_fields=update_fields)

        if not self.shortcut and self.id:
            self.shortcut = ShorthandUrl.compute_shortcut(self.id)
            self.save()

    def get_full_url(self, request):
        """
        Получение полного URL на сайте относительно запроса
        """
        return "http://%s/%s" % (request.hostname, self.shortcut)

    def get_redirect_url(self):
        return reverse('shortcut-redirect', kwargs={'shortcut': self.shortcut})

    def get_absolute_url(self):
        return reverse('shorthand:detail', kwargs={'pk': self.id})

    def __str__(self):
        return self.shortcut

    def __repr__(self):
        return '<%s.%s: %s>' % (self.__class__.__module__, self.__class__.__name__, self.shortcut)

shorthand/shorthand/forms.py
from django import forms
from . import models


class ShorthandUrlCreateForm(forms.ModelForm):
    """
    Форма для создания нового краткой ссылки
    """
    class Meta:
        model = models.ShorthandUrl
        fields = ('url',)

shorthand/shorthand/views.py
from django.core.urlresolvers import reverse_lazy
from django.views import generic
from django.views.generic import detail
from . import forms
from . import models


class HomepageView(generic.TemplateView):
    """
    Данный вид отображает главную страницу сайта

    :notice: Данный класс унаследован от TemplateView для расширения возможностей данного вида в дальнейшем.
    """
    template_name = 'homepage.html'

    def get_context_data(self, **kwargs):
        context = super(HomepageView, self).get_context_data(**kwargs)
        context.update({
            'form': forms.ShorthandUrlCreateForm(),
            'popular_shorthands': models.ShorthandUrl.objects.first_populars(),
        })
        return context


class ShorthandUrlCreateView(generic.CreateView):
    """
    Обработчик создания краткой ссылки
    """
    form_class = forms.ShorthandUrlCreateForm
    template_name = 'shorthands/create.html'


class ShorthandUrlDetailView(generic.DetailView):
    """
    Вид для отображения детальной информации о краткой ссылке
    """
    model = models.ShorthandUrl
    template_name = 'shorthands/detail.html'


class ShorthandUrlListView(generic.ListView):
    """
    Вид для отображения списка кратких ссылок
    """
    model = models.ShorthandUrl
    template_name = 'shorthands/list.html'
    paginate_by = 10

    def get_queryset(self):
        return super(ShorthandUrlListView, self).get_queryset().order_by_popularity()


class ShorthandUrlDeleteView(generic.DeleteView):
    """
    Вид для вывода сообщения об подтверждении удалении, и окончательном удалении после согласия с этим подтверждением.
    """
    model = models.ShorthandUrl
    template_name = 'shorthands/delete.html'
    success_url = reverse_lazy('shorthand:list')



class ShorthandUrlRedirectView(generic.RedirectView, detail.SingleObjectMixin):
    """
    Данный вид редиректит агента пользователя c краткой ссылки на полную. В качестве побочного эфекта увлечивается
    её количество просмотров.

    :notice: Заместо `slug` использован `shortcut`.
    :notice: В задании не чего не было сказано про способ редиректа, поэтому для лучшей отладки `permanent` выставлен
             в False
    """
    model = models.ShorthandUrl
    slug_field = 'shortcut'
    slug_url_kwarg = 'shortcut'
    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        short = self.get_object()
        short.increment()
        return short.url

shorthand/templates/base.html
<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8" />
        <title>Тестовое задания для NetAngels.ru</title>

        <!-- Bootstrap -->
        <link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'homepage' %}">Тестовое задание NetAngels.ru</a>
                </div>
            </div>
        </div>

         <div class="container" style="padding-top: 50px;">
            {% block content %}{% endblock %}
        </div><!-- /.container -->

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
        <script src="{{ STATIC_URL }}js/script.js"></script>
    </body>
</html>

shorthand/templates/homepage.html
{% extends "base.html" %}

{% block content %}
    <div class="starter-template">
        <h1>Главная страница</h1>
    </div>

    {% include "shorthands/blocks/form.html" %}

    <div>
        <h2>ТОП-20 самых популярных ссылок <small><a href="{% url 'shorthand:list' %}" class="label label-info">Все</a></small></h2>
        {% include "shorthands/blocks/list.html" with object_list=popular_shorthands %}
    </div>

{% endblock %}

shorthand/templates/shorthands/blocks/form.html
{% load widget_tweaks %}

<form action="{% url 'shorthand:create' %}" method="POST" role="form">
    <h2 class="lead">Форма создание краткой ссылки и 20 самых популярных ссылок</h2>

    {{ form.errors }}

    {% csrf_token %}
    <div class="form-group">
        {{ form.url.labe_tag }}
        {{ form.url|add_class:"form-control" }}
    </div>
    <input type="submit" class="btn btn-default" value="Получить краткий URL"/>
</form>

shorthand/templates/shorthands/blocks/list.html
{% load l10n %}

{% if object_list %}
    <table class="table table-striped">
        <tbody class="table-hover">
            {% for short in object_list %}
                <tr>
                    <td>
                        <a href="{{ short.get_redirect_url }}"><span class="glyphicon glyphicon-share"></span>{{ short.shortcut }}</a>
                    </td>
                    <td><span>{{ short.views_counter }}</span></td>
                    <td><span>{{ short.created_at|date:'d N Y H:i:s' }}</span></td>

                    {% if with_buttons %}
                        <td class="text-right">
                            <div class="btn-group">
                                <a type="button" class="btn btn-default" href="{% url 'shorthand:detail' pk=short.id %}"><span class="glyphicon glyphicon-zoom-in"></span></a>
                                <a type="button" class="btn btn-default" href="{% url 'shorthand:delete' pk=short.id %}"><span class="glyphicon glyphicon-remove"></span></a>
                            </div>
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}

{% endif %}

shorthand/templates/shorthands/blocks/pagination.html
{% comment %} https://djangosnippets.org/snippets/2741/ {% endcomment %}
{% if is_paginated %}
{% load i18n %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}{{ getvars }}{{ hashtag }}" class="prev">&lsaquo;&lsaquo; {% trans "previous" %}</a></li>
        {% else %}
            <li class="disabled prev"><a href="#">&lsaquo;&lsaquo; {% trans "previous" %}</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if page %}
                {% ifequal page page_obj.number %}
                    <li class="current page active"><a href="#">{{ page }}</a></li>
                {% else %}
                    <li><a href="?page={{ page }}{{ getvars }}{{ hashtag }}" class="page">{{ page }}</a></li>
                {% endifequal %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}{{ getvars }}{{ hashtag }}" class="next">{% trans "next" %} &rsaquo;&rsaquo;</a></li>
        {% else %}
            <li class="disabled next"><a href="#">{% trans "next" %} &rsaquo;&rsaquo;</a></li>
        {% endif %}
    </ul>
{% endif %}

shorthand/templates/shorthands/create.html
{% extends "base.html" %}

{% block content %}
    <h1>Создание краткой ссылки</h1>

    {% include "shorthands/blocks/form.html" %}
{% endblock %}

shorthand/templates/shorthands/delete.html
{% extends "base.html" %}

{% block content %}
    <h2>Удаление краткой ссылки</h2>
    <form action="" method="post">
        {% csrf_token %}
        <p>Вы уверены, что хотите удалить "{{ object }}"?</p>
        <input type="submit" value="Удалить" class="btn btn-danger" />
        <button class="js-history-back btn btn-default">Отмена</button>
    </form>
{% endblock %}

shorthand/templates/shorthands/detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ object }}<small><a href="{% url 'shorthand:list' %}" class="label label-info">Все</a></small></h1>

    <div class="list-group">
        <div class="list-group-item">
            <h4 class="list-group-item-heading">Ссылка</h4>
            <a href="{{ object.get_redirect_url }}" class="list-group-item-text"><span class="glyphicon glyphicon-share"></span>{{ object }}</a>
        </div>
        <div class="list-group-item">
            <h4 class="list-group-item-heading">Дата создания</h4>
            <p class="list-group-item-text">{{ object.created_at|date:'d N Y H:i:s' }}</p>
        </div>
        <div class="list-group-item">
            <h4 class="list-group-item-heading">Количество просмотров</h4>
            <p class="list-group-item-text">{{ object.views_counter }}</p>
        </div>
        <!-- Вывод скрыт. Так как в условиях задачи, не указанно выводить ли полную ссылку
        <div class="list-group-item">
            <h4 class="list-group-item-heading">Полная ссылка </h4>
            <a href="{{ object.url }}" class="list-group-item-text">{{ object.url }}</a>
        </div>
        -->
    </div>
{% endblock %}

shorthand/templates/shorthands/list.html
{% extends "base.html" %}

{% block content %}
    <div class="starter-template">
        <h1>Список кратких ссылок</h1>

        {% include "shorthands/blocks/list.html" with with_buttons=True %}
        {% include "shorthands/blocks/pagination.html" %}
    </div>
{% endblock %}